version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: gobank_postgres
    restart: always
    environment:
      POSTGRES_USER: shreyash
      POSTGRES_PASSWORD: eatsleepcode
      POSTGRES_DB: gobank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
